Credit/Controllers/BaseController.cs
using Credit.Data.Infrastructure;
using System.Web.Mvc;

namespace Credit.Controllers
{
    public class BaseController : Controller
    {

        #region

        internal UnitOfWork UnitOfWork = new UnitOfWork();

        #endregion
        
    }
}

Credit/Controllers/DebtController.cs
using Credit.Model;
using System.Net;
using System.Web.Mvc;

namespace Credit.Controllers
{
    public class DebtController : BaseController
    {
        
        #region Methods
        // GET: Debts?debtorId=5
        public ActionResult Index(int? debtorId)
        {
            Debtor debtor = null;
            var action = GetDebtorAction(debtorId, ref debtor);
            if (action != null)
            {
                return action;
            }

            ViewBag.DebtorId = debtorId;
            ViewBag.DebtorName = debtor.Name;
            var debts = UnitOfWork.DebtRepository.GetByDebotorId(debtorId.Value);
            return View(debts);
        }

        // GET: Debts/Details/5
        public ActionResult Details(int? id)
        {
            Debt debt = null;
            var action = GetDebtAction(id, ref debt);
            if (action != null)
            {
                return action;
            }
            return View(debt);
        }

        // GET: Debts/Create?debtorId=5
        public ActionResult Create(int? debtorId)
        {            
            Debtor debtor = null;
            var action = GetDebtorAction(debtorId, ref debtor);
            if (action != null)
            {
                return action;
            }

            Debt debt = new Debt()
            {
                DebtorId = debtorId.Value,
                Debtor = debtor
            };

            return View(debt);
        }

        // POST: Debts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StartDate,EndDate,DebtorId")] Debt debt)
        {
            if (ModelState.IsValid)
            {
                UnitOfWork.DebtRepository.Insert(debt);
                UnitOfWork.Save();
                return RedirectToAction("Index", new { debtorId = debt.DebtorId});
            }
            
            return View(debt);
        }

        // GET: Debts/Edit/5
        public ActionResult Edit(int? id)
        {
            Debt debt = null;
            var action = GetDebtAction(id, ref debt);
            if (action != null)
            {
                return action;
            }

            return View(debt);
        }

        // POST: Debts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StartDate,EndDate,DebtorId")] Debt debt)
        {
            if (ModelState.IsValid)
            {
                UnitOfWork.DebtRepository.Update(debt);
                UnitOfWork.Save();
                return RedirectToAction("Index", new { debtorId = debt.DebtorId });
            }
            
            return View(debt);
        }

        // GET: Debts/Delete/5
        public ActionResult Delete(int? id)
        {
            Debt debt = null;
            var action = GetDebtAction(id, ref debt);
            if (action != null)
            {
                return action;
            }

            return View(debt);
        }

        // POST: Debts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UnitOfWork.DebtRepository.Delete(id);
            UnitOfWork.Save();
            return RedirectToAction("Index");
        }

       
        #endregion

        #region Private Methods

        private ActionResult GetDebtorAction(int? debtorId, ref Debtor debtor) {
            if (debtorId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            debtor = UnitOfWork.DebtorRepository.GetById(debtorId);
            if (debtor == null)
            {
                return HttpNotFound();
            }

            return null;
        }

        private ActionResult GetDebtAction(int? debtId, ref Debt debt)
        {
            if (debtId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            debt = UnitOfWork.DebtRepository.GetById(debtId);
            if (debt == null)
            {
                return HttpNotFound();
            }

            return null;
        }

        #endregion
    }
}

Credit/Controllers/DebtorController.cs
using Credit.Data.Infrastructure;
using Credit.Model;
using System.Net;
using System.Web.Mvc;

namespace Credit.Controllers
{
    public class DebtorController : BaseController
    {
        // GET: Debtor
        public ActionResult Index()
        {
            var debtors = UnitOfWork.DebtorRepository.Get(null, null);
            return View(debtors);
        }

        // GET: Debtor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Debtor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Debtor debtor)
        {
            if (ModelState.IsValid) {
                UnitOfWork.DebtorRepository.Insert(debtor);
                UnitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(debtor);
        }

        // GET: Debtor/Edit/[:id]
        public ActionResult Edit(int? id)
        {
            if (null == id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Debtor debtor = UnitOfWork.DebtorRepository.GetById(id);
            if (null == debtor)
            {
                return HttpNotFound();
            }
            return View(debtor);
        }

        // POST: Debtor/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Debtor debtor)
        {
            if (ModelState.IsValid)
            {
                UnitOfWork.DebtorRepository.Update(debtor);
                UnitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(debtor);
        }

        // GET: Debtor/Delete/[:id]
        public ActionResult Delete(int? id)
        {
            if (null == id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Debtor debtor = UnitOfWork.DebtorRepository.GetById(id);
            if (null == debtor)
            {
                return HttpNotFound();
            }
            return View(debtor);
        }

        // POST: Debtor/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            
            UnitOfWork.DebtorRepository.Delete(id);
            UnitOfWork.Save();

            return RedirectToAction("Index");
            
        }

    }
}

Credit/Views/Debt/Create.cshtml
@model Credit.Model.Debt

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Deuda para @Model.Debtor.Name</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Debt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DebtorId)

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Percentage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Percentage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Percentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>
     
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Credit/Views/Debt/Delete.cshtml
@model Credit.Model.Debt

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Debt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Debtor.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Debtor.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Credit/Views/Debt/Details.cshtml
@model Credit.Model.Debt

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Debt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Debtor.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Debtor.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Credit/Views/Debt/Edit.cshtml
@model Credit.Model.Debt

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Deuda de @Model.Debtor.Name</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Debt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.DebtorId)

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Credit/Views/Debt/Index.cshtml
@model IEnumerable<Credit.Model.Debt>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deudas de @ViewBag.DebtorName</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { debtorId = ViewBag.DebtorId })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Debtor.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Debtor.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Credit/Views/Debtor/Create.cshtml
@model Credit.Model.Debtor

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Debtor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Credit/Views/Debtor/Delete.cshtml
@model Credit.Model.Debtor

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Debtor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Credit/Views/Debtor/Edit.cshtml
@model Credit.Model.Debtor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Debtor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Credit/Views/Debtor/Index.cshtml
@model IEnumerable<Credit.Model.Debtor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista deudores</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })            
        </td>
        <td>
            @Html.ActionLink("Mostrar Deudas", "Index", "Debt", new { debtorId = item.Id }, null)
        </td>
    </tr>
}

</table>

Credit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Deudores", "Index", "Debtor")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>